sim/mahasiswa/routes.py
from flask import Flask, render_template, redirect, request, url_for, Blueprint, flash, request
from sim.mahasiswa.forms import petugas_F, loginpetugas_F, editpetugas_F, pj_F, editpj_F, BasicForm
from sim.models import Tpetugas, Tpj
from sim import db, bcrypt
from flask_login import login_user, current_user, logout_user, login_required
from flask import Flask, render_template, request, redirect
from flaskext.mysql import MySQL
import os
import secrets
from sim import app
from PIL import Image


rpetugas = Blueprint('rpetugas', __name__)

@rpetugas.route("/")
def home():
    return render_template("home.html")

@rpetugas.route("/about")
def about():
    return render_template("about.html")

@rpetugas.route("/home2")
def home2():
    return render_template("home2.html")

@rpetugas.route("/data_petugas", methods=['GET', 'POST'])
def data_petugas():
    form = petugas_F()
    if form.validate_on_submit():
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        add_petugas = Tpetugas(nama=form.nama.data, email=form.email.data, password=pass_hash)
        db.session.add(add_petugas)
        db.session.commit()
        flash(f'Akun- {form.nama.data} berhasil daftar', 'info')
        return redirect(url_for('rpetugas.login_petugas'))
    return render_template("data-petugas.html", form=form)


@rpetugas.route("/login_petugas", methods=['GET', 'POST'])
def login_petugas():
    if current_user.is_authenticated:
        return redirect(url_for('rpetugas.home'))
    form = loginpetugas_F()
    if form.validate_on_submit():
        cekemail= Tpetugas.query.filter_by(email=form.email.data).first()
        if cekemail and bcrypt.check_password_hash(cekemail.password, form.password.data):
            login_user(cekemail)
            flash('Selamat Datang Kembali', 'warning')
            return redirect(url_for('rpetugas.akunpetugas'))
        else:
            flash('Login Gagal, Periksa NPM dan Password kembali!', 'danger')
    return render_template("login_petugas.html", form=form)


@rpetugas.route("/akunpetugas")
@login_required
def akunpetugas():
    return render_template('akunpetugas.html')


@rpetugas.route("/logout_petugas")
def logout_petugas():
    logout_user()
    return redirect(url_for('rpetugas.home'))

@rpetugas.route("/pemberitahuan")
@login_required
def pemberitahuan():
    #return redirect(url_for('rpetugas.pemberitahuan'))
    dt_pj=Tpj.query.all()
    return render_template('pemberitahuan.html', dt_pj=dt_pj)


#simpan foto
def simpan_foto(form_foto):
    random_hex= secrets.token_hex(8)
    f_name, f_ext= os.path.splitext(form_foto.filename)
    foto_fn=random_hex + f_ext
    foto_path= os.path.join(app.root_path, 'sim/static/foto', foto_fn)
    ubah_size=(300,300)
    j=Image.open(form_foto)
    j.thumbnail(ubah_size)
    j.save(foto_path)
    #form_foto.save(foto_path)
    return foto_fn

@rpetugas.route("/edit_petugas", methods=['GET', 'POST'])
@login_required
def edit_petugas():
    form=editpetugas_F()
    if form.validate_on_submit():
        if form.foto.data:
            file_foto=simpan_foto(form.foto.data)
            current_user.foto = file_foto
        pass_hash=bcrypt.generate_password_hash(form.password.data).decode('UTF-8')
        current_user.nama=form.nama.data
        current_user.email=form.email.data
        current_user.password=pass_hash
        db.session.commit()
        flash('Data Berhasil di Ubah','warning')
        return redirect(url_for('rpetugas.edit_petugas'))
    elif request.method=="GET":
        form.nama.data=current_user.nama
        form.email.data=current_user.email

    return render_template("edit_petugas.html", form=form )


@rpetugas.route("/pj", methods=['GET', 'POST'])
@login_required
def pj():
    dt_pj=Tpj.query.filter_by(petugas_id=current_user.id)
    form=pj_F()
    if form.validate_on_submit():
        #tambah data pengaduan
        add_pj=Tpj(nama=form.nama.data, nohp=form.nohp.data, kategori=form.kategori.data, kategori2=form.kategori2.data, alamat=form.alamat.data, judul_buku=form.judul_buku.data,
        jumlahbuku=form.jumlahbuku.data,penerbit=form.penerbit.data,nama_petugas=form.nama_petugas.data, petugas=current_user)
        db.session.add(add_pj)
        db.session.commit()
        flash('Data Berhasil di Tambahkan','warning')
        return redirect(url_for('rpetugas.pj'))
    return render_template('peminjaman.html', form=form, dt_pj=dt_pj)


@rpetugas.route("/pj/<int:ed_id>/update", methods=['GET', 'POST'])
@login_required
def update_pj(ed_id):
    form=editpj_F()
    dt_pj=Tpj.query.get_or_404(ed_id)
    if request.method=="GET":
        form.nama.data=dt_pj.nama
        form.nohp.data=dt_pj.nohp
        form.kategori.data=dt_pj.kategori
        form.kategori2.data=dt_pj.kategori2
        form.alamat.data=dt_pj.alamat
        form.judul_buku.data=dt_pj.judul_buku
        form.jumlahbuku.data=dt_pj.jumlahbuku
        form.penerbit.data=dt_pj.penerbit
        form.nama_petugas.data=dt_pj.nama_petugas

    elif form.validate_on_submit():
        dt_pj.nama= form.nama.data
        dt_pj.nohp=form.nohp.data
        dt_pj.kategori=form.kategori.data
        dt_pj.kategori2=form.kategori2.data
        dt_pj.alamat=form.alamat.data
        dt_pj.judul_buku=form.judul_buku.data
        dt_pj.jumlahbuku=form.jumlahbuku.data
        dt_pj.penerbit=form.penerbit.data
        dt_pj.nama_petugas=form.nama_petugas.data
        db.session.commit()
        flash('Data Berhasil di Ubah', 'warning')
        return redirect(url_for('rpetugas.pj'))
    return render_template('edit_peminjaman.html', form=form)

@rpetugas.route("/delete/<id>", methods=['GET', 'POST'])
@login_required
def hapus_pj(id):
    h_pj=Tpj.query.get(id)
    db.session.delete(h_pj)
    db.session.commit()
    flash('Data Berhasil di Hapus', 'warning')
    return redirect(url_for('rpetugas.pemberitahuan'))


@rpetugas.route("/pj/<int:ed_id>/detail_pj", methods=['GET', 'POST'])
@login_required
def detail_pj(ed_id):
    dt_pj=Tpj.query.get_or_404(ed_id)
    return render_template('detail_pj.html', dt_pj=dt_pj)

@rpetugas.route("/pj/<int:ed_id>/search_pj", methods=['GET', 'POST'])
@login_required
def search_pj(ed_id):
    form = BasicForm()
    dt_pj=Tpj.query.get_or_404(ed_id)
    if request.method=="GET":
        return redirect(url_for('rpetugas.pj'))
    return render_template('pemberitahuan.html', dt_pj=dt_pj)

sim/templates/about.html
{% extends "base.html" %}

{% block konten%}

<h1>Tentang kami</h1>
<p>Metana adalah website yang saya buat untuk kalian agar kalian dapat mengutarakan keluhan ataupun memberikan masukan</p>
<p>Website ini masih banyak kekurangan atau masih dalam tahap pengembangan</p>
<p>Terima Kasih :)</p>

{% endblock %}

sim/templates/akunpetugas.html
{% extends "base.html" %}

{% block konten%}

<div class="jumbotron">
    <br>
    <h1 class="display-4">Hola {{current_user.nama}}!</h1>
    <p class="lead">Thank you for sign in and Welcome to my website</p>
    <hr class="my-4">
    <p>Klik untuk memulai pengaduan anda.</p>
    <a class="btn btn-warning btn-lg" href="{{url_for('rpetugas.pj')}}" role="button">Mulai Pinjam</a>
</div>
{% endblock %}

sim/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Metana-website</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{{ url_for ('static', filename='css/bootstrap.min.css')}}" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for ('static', filename='css/style.css')}}">
</head>

<body class="bod">
    <div id="main">
        <nav class="navbar navbar-expand-lg navbar-light mt-4 ">
            <div class="container-fluid" style="margin-left: 30px;margin-right: 30px;">
                <a class="navbar-brand" id="sma10" href="#"><img id="sma10" src="{{url_for('static', filename='foto/smaten.png')}}" width="40px" height="40px"> </a>
                <label for="sma10" id="sma10"> SMA NEGERI 10 KOTA TERNATE</label>
                
                <button class="navbar-toggler ms-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                    aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item fs-5" style="padding-right: 120px;">

                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item fs-5">
                            <a class="nav-link actives" aria-current="page"href="{{url_for('rpetugas.akunpetugas')}}"><b>Home</b></a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.about')}}">About</a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.pj')}}">Peminjaman</a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.pemberitahuan')}}">Pemberitahuan</a>
                        </li>
                        {%else%}
                        <li class="nav-item fs-5">
                            <a class="nav-link actives" aria-current="page"href="{{url_for('rpetugas.home')}}"><b>Home</b></a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.about')}}">About</a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.login_petugas')}}">Login</a>
                        </li>
                        {%endif%}
                        
                        <li class="nav-item" style="margin-right: 200px;">
                        </li>
                        {% if current_user.is_authenticated %}
                        <div class="iconemail d-flex md-4">
                            <a class="nav-link d-flex" id="akun" href="{{url_for('rpetugas.edit_petugas')}}">
                            <li class="nav-item fs-5 d-flex" style="margin-right: 5px;">
                            Akun
                            </li>
                            <div class="shadow bg-white rounded" style="border: 2px solid black;
                            border-radius: 40px;">
                                <div class="card" style="width: 2rem;">
                                    <li class="nav-item">
                                    <img src="{{url_for('static', filename='foto/' + current_user.foto)}}" class="card-img-top"
                                    alt="..." width="20px" height="20px">
                                    </li>
                                </div>
                            </div>
                            </a>
                        </div>

                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.logout_petugas')}}">Logout</a>
                        </li>

                        {%else%}
                        {%endif%}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container yy logint" style="margin-top: 40px;position:static; align-items: center; justify-content: center; width: 100%;">
        <div class="row">
            <div class="col-md-12">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <!--flash-->
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}

                    <div class="alert alert-{{category}}">
                        {{message}}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}



                    {%block konten%}

                    {%endblock%}
                </div>
            </div>
            {% if current_user.is_authenticated %}
            <div class="col-md-4">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <div class="card" style="width: 14rem;">
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><a href="{{url_for('rpetugas.akunpetugas')}}">Dasboard</a>
                        </li>
                        <li class="list-group-item"><a href="{{url_for('rpetugas.pj')}}">Peminjaman</a></li>
                    </ul>
                    <div class="card-body">
                        <a href="{{url_for('rpetugas.edit_petugas')}}" class="card-link">Update Profil</a>
                    </div>
                    {% else %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-static-bottom">
        <p class="copy" style="background-color: rgb(23, 17, 17); color: white;padding-top: 0;" align="center">Copyright_by_ummu</p>
    </div>
    
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <p class="copy" style="background-color: rgb(23, 17, 17); color: white; padding-top: 0;" align="center">Copyright_by_ummu</p>
    </div>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
    crossorigin="anonymous"></script>
<script src="{{ url_for ('static', filename='css/bootstrap.min.js')}}"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
    crossorigin="anonymous"></script>

</html>

sim/templates/data-petugas.html
{% extends "base.html" %}

{% block konten%}
<h1>Daftar Akun</h1>
<form method="POST">
    {{form.hidden_tag()}}
    <div class="form-group">
        {{form.nama.label(class="form-control-label")}}
        {% if form.nama.errors %}
        {{form.nama(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.nama.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}

        {{form.nama(class="form-control")}}

        {%endif%}
    </div>
    <br>

    <div class="form-group">
        {{form.email.label(class="form-control-label")}}
        {% if form.email.errors %}
        {{form.email(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.email.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}

        {{form.email(class="form-control")}}

        {%endif%}
    </div>
    <br>
    <div class="form-group">
        {{form.password.label(class="form-control-label")}}
        {% if form.password.errors %}
        {{form.password(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.password.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}

        {{form.password(class="form-control")}}

        {%endif%}

    </div>

    <br>
    <div class="form-group">
        {{form.kon_pass.label(class="form-control-label")}}
        {% if form.kon_pass.errors %}
        {{form.kon_pass(class="form-control is-invalid")}}

        <div class="invalid-feedback">
            {% for error in form.kon_pass.errors %}
            <span>{{error}}</span>
            {% endfor %}
        </div>
        {%else%}

        {{form.kon_pass(class="form-control")}}

        {%endif%}

    </div>
    <br>
    <div class="form-group">
        {{form.submit(class="btn btn-primary")}}
    </div>
</form>

{% endblock %}

sim/templates/login_petugas.html
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Metana-website</title>
    <link href="{{ url_for ('static', filename='css/bootstrap.min.css')}}" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for ('static', filename='css/style.css')}}">
</head>

<body class="bod">
    <div id="main">
        <nav class="navbar navbar-expand-lg navbar-light mt-4 ">
            <div class="container-fluid" style="margin-left: 30px;margin-right: 30px;">
                <a class="navbar-brand" id="sma10" href="#"><img id="sma10" src="{{url_for('static', filename='foto/smaten.png')}}" width="40px" height="40px"> </a>
                <label for="sma10" id="sma10"> SMA NEGERI 10 KOTA TERNATE</label>
                
                <button class="navbar-toggler ms-3" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                    aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarScroll">
                    <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                        <li class="nav-item fs-5" style="padding-right: 120px;">

                        </li>
                        {% if current_user.is_authenticated %}
                        <li class="nav-item fs-5">
                            <a class="nav-link actives" aria-current="page"href="{{url_for('rpetugas.akunpetugas')}}"><b>Home</b></a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.about')}}">About</a>
                        </li>
                        {%else%}
                        <li class="nav-item fs-5">
                            <a class="nav-link actives" aria-current="page"href="{{url_for('rpetugas.home')}}"><b>Home</b></a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.about')}}">About</a>
                        </li>
                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.login_petugas')}}">Login</a>
                        </li>
                        {%endif%}
                        
                        <li class="nav-item" style="margin-right: 200px;">
                        </li>
                        {% if current_user.is_authenticated %}
                        <div class="iconemail d-flex md-4">
                            <a class="nav-link d-flex" id="akun" href="{{url_for('rpetugas.about')}}">
                            <li class="nav-item fs-5 d-flex" style="margin-right: 5px;">
                            Akun
                            </li>
                            <div class="shadow bg-white rounded" style="border: 2px solid black;
                            border-radius: 40px;">
                                <div class="card" style="width: 2rem;">
                                    <li class="nav-item">
                                    <img src="{{url_for('static', filename='foto/' + current_user.foto)}}" class="card-img-top"
                                    alt="..." width="20px" height="20px">
                                    </li>
                                </div>
                            </div>
                            </a>
                        </div>

                        <li class="nav-item fs-5">
                            <a class="nav-link" href="{{url_for('rpetugas.logout_petugas')}}">Logout</a>
                        </li>

                        {%else%}
                        {%endif%}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    <div class="container yy" style="margin-top: 40px;position:static; align-items: center; justify-content: center; width: 100%;">
        <div class="row">
            <div class="col-md-6">
                <div class="shadow p-3 mb-5 bg-white rounded">
                    <!--flash-->
                    {% with messages= get_flashed_messages(with_categories=true) %}
                    {% if messages %}
                    {% for category, message in messages %}

                    <div class="alert alert-{{category}}">
                        {{message}}
                    </div>
                    {% endfor %}
                    {% endif %}
                    {% endwith %}
                    <h1>LOGIN</h1>
                    <form method="POST">
                        {{form.hidden_tag()}}
                        <div class="form-group">
                            {{form.email.label(class="form-control-label")}}
                            {% if form.email.errors %}
                            {{form.email(class="form-control is-invalid")}}

                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                <span>{{error}}</span>
                                {% endfor %}
                            </div>
                            {%else%}

                            {{form.email(class="form-control")}}

                            {%endif%}

                        </div>
                        <br>

                        <div class="form-group">
                            {{form.password.label(class="form-control-label")}}
                            {% if form.password.errors %}
                            {{form.password(class="form-control is-invalid")}}

                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                <span>{{error}}</span>
                                {% endfor %}
                            </div>
                            {%else%}

                            {{form.password(class="form-control")}}

                            {%endif%}

                        </div>

                        <br>
                        <div class="form-group">
                            {{form.submit(class="btn btn-primary")}}
                        </div>
                        <br>
                        <span> <a href="{{url_for('rpetugas.data_petugas')}}">Daftar Akun</a></span>
                    </form>
                </div>
            </div>
            <div class="col-1">

            </div>
            <div class="bacabuku col-5 p-3 mb-5">
                <h1 align="center">Ayo Baca Buku!!!</h1>
                <p align="center">Buku adalah kumpulan/himpunan kertas atau lembaran yang tertulis
                    atau mengandung tulisan. Bahan-bahan tersebut bisa berbentuk potongan
                    yang terbuat dari kayu, kertas bahkan gading gajah. Kumpulan ini dihimpun
                    atau dijilid menjadi satu pada salah satu ujungnya dan berisi tulisan, gambar atau tempelan. </p>
            </div>
        </div>
    </div>
    <div class="navbar navbar-inverse navbar-fixed-bottom">
        <p class="copy" style="background-color: rgb(23, 17, 17); color: white; padding-top: 0;" align="center">Copyright_by_ummu</p>
    </div>
    </div>
</body>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
    integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
    crossorigin="anonymous"></script>
<script src="{{ url_for ('static', filename='css/bootstrap.min.js')}}"
    integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
    crossorigin="anonymous"></script>

</html>

sim/templates/pemberitahuan.html
{% extends "base.html" %}

{% block konten%}
<div class="jumbotron">
    <!--div class="container col mt-6" style="margin-top: 40px; width: 100%; margin-left:-100px;" >
      <div class="row d-flex" >
            <div class="col-md-6">
                <div class="formulir">
                    <form class="d-flex " style="display: center; align-content:center; padding-left:80px;">
                        <input class="form-control me-3" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-primary" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </div>
    </div-->
    <script>
        function klik_hapus(value) {
            let valid_link = document.getElementById('del-hapus')
            valid_link.href = "/delete/" + value
        }
    </script>
    <hr class="my-4">
    <h4>Data Peminjaman</h4>
    <div class="table-responsive">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Tgl</th>
                    <th scope="col">Nama</th>
                    <th scope="col">Kelas</th>
                    <th scope="col">Jurusan</th>
                    <th scope="col">Judul Buku</th>
                    <th scope="col">Jumlah Buku</th>
                    <th scope="col">Penerbit</th>
                    <th scope="col">Nama Petugas</th>
                    <th scope="col">Edit</th>
                    <th scope="col">Hapus</th>
                </tr>
            </thead>
            <tbody>
                {% for data in dt_pj %}
                <tr>
                    <th><a href="{{url_for('rpetugas.detail_pj', ed_id=data.id)}}"><svg
                                xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-arrow-up-left-square-fill" viewBox="0 0 16 16">
                                <path
                                    d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm8.096 10.803L6 6.707v2.768a.5.5 0 0 1-1 0V5.5a.5.5 0 0 1 .5-.5h3.975a.5.5 0 1 1 0 1H6.707l4.096 4.096a.5.5 0 1 1-.707.707z" />
                            </svg></a></th>
                    <td>{{data.tgl_post}}</td>
                    <td>{{data.nama}}</td>
                    <td>{{data.kategori}}</td>
                    <td>{{data.kategori2}}</td>
                    <td>{{data.judul_buku}}</td>
                    <td>{{data.jumlahbuku}}</td>
                    <td>{{data.penerbit}}</td>
                    <td>{{data.nama_petugas}}</td>
                    <td><a class="btn btn-outline-success" href="{{url_for('rpetugas.update_pj', ed_id=data.id)}}">Edit</a> </td>
                    <td><a class="btn btn-danger" href="/delete/{{data.id}}" onclick="return confirm('Yakin Data Mau di Hapus?')">Hapus</a></td>
                    {% endfor %}
                    <!--modals hapus-->
                    <div class="modal" tabindex="-1" role="dialog" id=modals-hapus>
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title">Modal title</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <p>Modal body text goes here.</p>
                                </div>
                                <div class="modal-footer">
                                    <form action="">
                                        <a class="btn btn-warning" id="del-hapus">Hapus</a>
                                    </form>
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}